server:
  port: ${PORT:8080}

spring:
  application:
    name: auth

  datasource:
    url: "jdbc:h2:mem:test;DB_CLOSE_DELAY=-1"
    driver-class-name: org.h2.Driver
  jpa:
    database: h2
    show-sql: false
    hibernate:
      ddl-auto: create-drop

management:
  metrics:
    export:
      influx:
        step: 5s
        uri: http://localhost:8086
        db: metrics
        user-name: user
        password: user